### ISSUE TITLE
无法用maven下载依赖包

### ISSUE THREAD

**Issue by xiaoCong2014** [JeffLi1993/fast-framework#4]
部分下载不到，能直接放到项目里，或者用网盘吗？

**Comment by JeffLi1993** [comment]
请问具体哪个依赖包下不了？

是不是 网络问题？修改maven根目录下的conf文件夹中的setting.xml文件，内容如下：http://blog.csdn.net/u010717403/article/details/52188496

**Comment by xiaoCong2014** [comment]
你可以把 jar 依赖包都下载好，然后整理到GitHub的项目里吗？（最好再把托管项目到
中国版GitHub -->Coding，备份到 CSDN下载站，百度云 网盘） 在国内，依赖包要下载很久，甚至无法下载。
我的环境：Maven 3.3.9 ，最新版
之前用 Maven 3.3.1，也卡住，只是卡在不同的 jar 包（就是因为卡住所以我才换最新版的Maven）
不知什么时候才能下载好
用你的方法，切换到 **阿里云** ，但卡在：
Downloaded: http://maven.aliyun.com/nexus/content/groups/public/org/mortbay/jasper/apache-jsp/8.0.9.M3/apache-jsp-8.0.9.M3.jar (934 KB at 13.7 KB/sec)
1553/1724 KB

过了半小时后，又卡住：
Downloading: https://oss.sonatype.org/content/groups/jetty/org/eclipse/jetty/orbit/org.eclipse.jdt.core/3.8.2.v20130121/org.eclipse.jdt.core-3.8.2.v20130121.jar
292/1724 KB
很明显，这是在访问 **国外的服务器** ，所以慢得离谱

我执行：
cd fast-sample // cd 到 sample 案例工程根目录
mvn jetty:run  // 启动 sample 工程
过了1,2 个小时后，报错：
[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.11.v20150529:run (default-cli) on project fast-sample: Execution default-cli of goal org.eclipse.jetty:jetty-maven-plugin:9.2.11.v20150529:run failed: Plugin org.eclipse.jetty:jetty-maven-plugin:9.2.11.v20150529 or one of its dependencies could not be resolved: Could not transfer artifact org.eclipse.jetty.orbit:org.eclipse.jdt.core:jar:3.8.2.v20130121 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public/): GET request of: org/eclipse/jetty/orbit/org.eclipse.jdt.core/3.8.2.v20130121/org.eclipse.jdt.core-3.8.2.v20130121.jar from alimaven failed: Connection reset -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
